### ISSUE TITLE
lex.yy.c compilation errors

### ISSUE THREAD

**Issue by mgavioli** [djw-zr/ZR#3]
Context: Linux Mint 21.1, gcc 11.3.0, ld 2.38, make 4.3; ZR version 0.6.

When compiling the code, I receive 3 error messages, all directly or indirectly referring to `lex.yy.c`:
```
/usr/bin/ld: lex.yy.o:/home/mmg/Documents/projects/C_projects/ZeroRails/ZR/lex.yy.c:326: multiple definition of `yyin'; sigscr.o:/home/mmg/Documents/projects/C_projects/ZeroRails/ZR/src/input/sigscr.c:92: first defined here
/usr/bin/ld: lex.yy.o:/home/mmg/Documents/projects/C_projects/ZeroRails/ZR/lex.yy.c:326: multiple definition of `yyout'; sigscr.o:/home/mmg/Documents/projects/C_projects/ZeroRails/ZR/src/input/sigscr.c:92: first defined here
/usr/bin/ld: lex.yy.o:/home/mmg/Documents/projects/C_projects/ZeroRails/ZR/bas.l:57: multiple definition of `string'; zr.o:/home/mmg/Documents/projects/C_projects/ZeroRails/ZR/src/input/load_wagon_file.c:26: first defined here`
```
As last time I dealt with Lex/Yacc was 30+ years ago, I no longer have an idea of what it is actually happening.

The first two errors **seem** clear: `yyin` and `yyout` are actually defined in both files (`input/lex.yy.c` and `input/sigscr.c`); as in `input/sigscr.c` `yyin` and `yyout` are only used in the `int read_sigscr_file(char*, char*)` function, the two variables could be moved there from the global position and those two errors would go away.

But the third is quite unclear to me: I tried renaming the variable defined in `input/load_wagon_file.c`, but whatever I put there, it also pops up in `input/lex.yy.c` (which it then presumably generated by some compilation pass not obvious from the `makefile`). So there must be something else going on I don't understand, potentially relating to the first two errors too.

Any suggestion to reach a successful compilation is welcome!

**Comment by djw-zr** [comment]
Context: OpenSuSE 15.3 : gcc 7.5.0, ld 2.39.0, make 4.2.1

One solution may be for you to try gcc 7 - something probably changed in the compiler.  Otherwise :

1.  yyin and yyout 

These are defined in sigscr.c, line 92:

      FILE   *yyin, *yyout ;

They are defined twice in lex_yy.c, at lines 159 and 327

      extern FILE *yyin, *yyout;
      FILE *yyin = NULL, *yyout = NULL;

It is probably a bad idea to edit lex.yy.c as that is generated by flex.  Instead I suggest you try replacing the line in sigscr.c by,

        extern FILE *yyin, *yyout;


2. string

This is defined in lex.yy.c at line 634 and in load_wagon_file.c at line 26.  Both are used by routines within the file.  Again it is probably not a good idea to change lex.yy.c,  Instead try adding the 'static' specifier to line 26 of load_wagon_file.c.  This means that the variable is for private use by code within the same file.

       static char string[4096]

I've tried these out with my current version of the code.  A quick test showed that, after the changes, ZR still compiles and runs without problems on my system.

**Comment by mgavioli** [comment]
Thanks for the detailed reply.

after implementing the changes you suggest, the programme compiles and run correctly (I have only tried the "check files" run, not the visualising run yet: one step at a time!).

I assume the issue can be closed. 

As it is better not to diverge the code base(s) and these two small changes work on both our systems, shall I make a pull request including them?

On another plane, the issue tracker is rather specific (and should remain as such!); can you suggest a context to discuss details (and collateral topics like OR and Linux) which are not really issues? Thanks.

**Comment by djw-zr** [comment]
Yes, make a pull request, but there has been one new commit since 0.6, so you may need to deal with that first.  Please keep the title of your new commit as short as possible . In my browser Github shows about sixty characters.  The number shown by my version of gitk is about the same. 

I'll wait until I get your pull request before closing the issue.  

For discussions I would suggest joining "www.elvastower.com", the web site used by many of the OpenRails developers.  I started a page "Progress with a GNU/OpenGL version of Openrails" with updates on ZR.  However it comes under "OR-News".  There is no obvious forum for a discussion about Linux.  The best match appears to be "Elvas Tower>software development>contributed software>software - other utilities".  Linux is not exactly a utility, but as the forum has only had five new topics in the last year I do not think anyone should complain.

**Comment by mgavioli** [comment]
Pull requested posted. Sorry for the delay, the "real world" knocked at the door!
